# Template — generated by deploy script from Terraform outputs.
# The SASL_JAAS_CONFIG value is built from the Event Hubs connection string.
#
# DO NOT commit the rendered version of this file.
#
# Generate with:
#   CONN_STR=$(terraform -chdir=infra/terraform output -raw eventhubs_connection_string 2>/dev/null || echo "PLACEHOLDER")
#   sed "s|__CONN_STR__|${CONN_STR}|g" k8s/eventhubs-sasl-secret.yaml.tpl > k8s/eventhubs-sasl-secret.yaml
#   kubectl apply -f k8s/eventhubs-sasl-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: eventhubs-sasl-secret
  namespace: ads-platform
type: Opaque
stringData:
  SASL_JAAS_CONFIG: >-
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="$ConnectionString"
    password="__CONN_STR__";
